# Generated by Django 3.1.3 on 2020-11-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
            ],
        ),
    ]
