# Generated by Django 3.1.3 on 2020-11-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20201123_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfressionalExperience',
            new_name='ProfessionalExperience',
        ),
    ]
